-- EAT60 operations upgrade. Run once in Supabase SQL Editor after eat60_supabase.sql.
-- Safe to rerun. Admin decisions stay protected by is_admin() and existing RLS policies.

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.settings
  add column if not exists store_online boolean not null default true,
  add column if not exists offline_message text not null default 'We are offline right now. Please check back soon.',
  add column if not exists min_delivery_km numeric(6,2) not null default 2,
  add column if not exists delivery_per_km int not null default 5,
  add column if not exists free_delivery_minimum int not null default 0,
  add column if not exists delivery_free boolean not null default false,
  add column if not exists max_delivery_km numeric(6,2) not null default 5,
  add column if not exists about_founder_name text not null default '',
  add column if not exists about_founder_photo_url text not null default '',
  add column if not exists about_founder_instagram_url text not null default '',
  add column if not exists about_founder_portfolio_url text not null default '',
  add column if not exists about_outlet_links jsonb not null default '{}'::jsonb,
  add column if not exists offer_title text not null default 'OFFER OF THE DAY',
  add column if not exists offer_message text not null default 'GRAB THIS OFFER BEFORE IT ENDS',
  add column if not exists offer_ends_at timestamptz;

alter table public.brands
  add column if not exists about_category text not null default '',
  add column if not exists about_tagline text not null default '',
  add column if not exists zomato_url text not null default '',
  add column if not exists swiggy_url text not null default '';
update public.brands set about_category='Pizza',about_tagline='Out-of-this-world cheese.' where id='pg' and about_category='';
update public.brands set about_category='Pizza',about_tagline='Hot, fresh and always glowing.' where id='ro' and about_category='';
update public.brands set about_category='Burgers, sandwiches, Maggie',about_tagline='The town where cheese is the mayor.' where id='ct' and about_category='';
update public.brands set about_category='Chinese',about_tagline='Every wok has a tale to toss.' where id='ws' and about_category='';
update public.brands set about_category='Wraps and kathi rolls',about_tagline='Roll up, roll in.' where id='wr' and about_category='';

alter table public.orders
  add column if not exists customer_name text,
  add column if not exists delivery_fee_before_discount int not null default 0,
  add column if not exists delivery_distance_km numeric(6,2),
  add column if not exists gst_amount int not null default 0,
  add column if not exists order_stage text not null default 'pending',
  add column if not exists accepted_at timestamptz,
  add column if not exists ready_at timestamptz,
  add column if not exists payment_received_at timestamptz,
  add column if not exists payment_type text,
  add column if not exists rejection_reason text,
  add column if not exists coupon_code text,
  add column if not exists coupon_discount int not null default 0;
alter table public.orders add column if not exists dispatched_at timestamptz;

update public.orders
set order_stage = case status::text
  when 'preparing' then 'preparing'
  when 'out_for_delivery' then 'out_for_delivery'
  when 'delivered' then 'delivered'
  when 'cancelled' then 'cancelled'
  else 'pending'
end;

do $$ begin
  if not exists (select 1 from pg_constraint where conname='orders_stage_check' and conrelid='public.orders'::regclass) then
    alter table public.orders add constraint orders_stage_check
      check (order_stage in ('pending','accepted','preparing','ready','out_for_delivery','payment_received','delivered','rejected','cancelled'));
  end if;
  if not exists (select 1 from pg_constraint where conname='orders_payment_type_check' and conrelid='public.orders'::regclass) then
    alter table public.orders add constraint orders_payment_type_check
      check (payment_type is null or payment_type in ('cash','upi','card','online','other'));
  end if;
end $$;

create index if not exists orders_stage_created_idx on public.orders(order_stage, created_at);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

create table if not exists public.order_stage_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  stage text not null,
  note text,
  changed_by uuid references auth.users(id) on delete set null,
  occurred_at timestamptz not null default now()
);
create index if not exists order_stage_events_order_idx on public.order_stage_events(order_id,occurred_at);
alter table public.order_stage_events enable row level security;
drop policy if exists "customer and admin read order timeline" on public.order_stage_events;
create policy "customer and admin read order timeline" on public.order_stage_events for select using (user_id=auth.uid() or public.is_admin());
grant select on public.order_stage_events to authenticated;
grant usage,select on sequence public.order_stage_events_id_seq to authenticated;

create or replace function public.capture_order_stage_event()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if tg_op='INSERT' then
    insert into order_stage_events(order_id,user_id,stage,note,changed_by,occurred_at)
    values(new.id,new.user_id,new.order_stage,'Order received',auth.uid(),new.created_at);
  elsif new.order_stage is distinct from old.order_stage then
    insert into order_stage_events(order_id,user_id,stage,note,changed_by,occurred_at)
    values(new.id,new.user_id,new.order_stage,
      case when new.order_stage='rejected' then coalesce(new.rejection_reason,'Order rejected')
           when new.order_stage='payment_received' then 'Payment received · '||coalesce(new.payment_type,'')
           else null end,
      auth.uid(),now());
  end if;
  return new;
end $$;
drop trigger if exists order_stage_event_log on public.orders;
create trigger order_stage_event_log after insert or update of order_stage on public.orders
for each row execute function public.capture_order_stage_event();

insert into public.order_stage_events(order_id,user_id,stage,note,occurred_at)
select o.id,o.user_id,o.order_stage,'Timeline tracking enabled',o.created_at
from public.orders o where not exists(select 1 from public.order_stage_events e where e.order_id=o.id);

create table if not exists public.item_extras (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.menu_items(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 80),
  price int not null check (price >= 0),
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.order_items add column if not exists extra_details jsonb not null default '[]'::jsonb;
alter table public.streak_rewards add column if not exists is_active boolean not null default true;

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique check (code = upper(code) and code ~ '^[A-Z0-9_-]{3,32}$'),
  description text not null default '',
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value int not null check (discount_value > 0),
  minimum_order int not null default 0 check (minimum_order >= 0),
  maximum_discount int check (maximum_discount is null or maximum_discount > 0),
  usage_limit int check (usage_limit is null or usage_limit > 0),
  per_user_limit int not null default 1 check (per_user_limit > 0),
  used_count int not null default 0 check (used_count >= 0),
  starts_at timestamptz,
  expires_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  check (discount_type <> 'percent' or discount_value <= 100),
  check (expires_at is null or starts_at is null or expires_at > starts_at)
);

create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.coupons(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  discount_amount int not null check (discount_amount >= 0),
  redeemed_at timestamptz not null default now()
);
create index if not exists coupon_redemptions_user_coupon_idx on public.coupon_redemptions(coupon_id,user_id);
alter table public.item_extras enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_redemptions enable row level security;

drop policy if exists "read item extras" on public.item_extras;
create policy "read item extras" on public.item_extras for select using (true);
drop policy if exists "admin item extras" on public.item_extras;
create policy "admin item extras" on public.item_extras for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin coupons" on public.coupons;
create policy "admin coupons" on public.coupons for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin coupon redemptions" on public.coupon_redemptions;
create policy "admin coupon redemptions" on public.coupon_redemptions for select using (public.is_admin());
grant select on public.item_extras to anon, authenticated;
grant insert, update, delete on public.item_extras to authenticated;
grant select, insert, update, delete on public.coupons to authenticated;
grant select on public.coupon_redemptions to authenticated;
grant usage, select on sequence public.item_extras_id_seq, public.coupons_id_seq, public.coupon_redemptions_id_seq to authenticated;

create or replace function public.customer_available_coupons()
returns table(
  code text,
  description text,
  discount_type text,
  discount_value int,
  minimum_order int,
  maximum_discount int,
  expires_at timestamptz
)
language sql stable security definer set search_path=public as $$
  select c.code,c.description,c.discount_type,c.discount_value,c.minimum_order,c.maximum_discount,c.expires_at
  from public.coupons c
  where auth.uid() is not null
    and c.is_active
    and (c.starts_at is null or now()>=c.starts_at)
    and (c.expires_at is null or now()<c.expires_at)
    and (c.usage_limit is null or c.used_count<c.usage_limit)
    and (select count(*) from public.coupon_redemptions r where r.coupon_id=c.id and r.user_id=auth.uid())<c.per_user_limit
  order by c.created_at desc
$$;

create or replace function public.claim_streak_reward(p_milestone int)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_gift text; v_best int;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  select gift into v_gift from streak_rewards where milestone=p_milestone and is_active;
  if v_gift is null then raise exception 'This streak reward is not available'; end if;
  select greatest(coalesce(longest_streak,0),coalesce(streak,0)) into v_best from profiles where id=auth.uid();
  if coalesce(v_best,0)<p_milestone then raise exception 'Keep your order streak going to unlock this reward'; end if;
  insert into user_rewards(user_id,milestone,gift) values(auth.uid(),p_milestone,v_gift) on conflict(user_id,milestone) do nothing;
  update user_rewards set claimed=true where user_id=auth.uid() and milestone=p_milestone and claimed=false;
  return jsonb_build_object('milestone',p_milestone,'gift',v_gift,'claimed',true);
end $$;
grant execute on function public.claim_streak_reward(int) to authenticated;

create or replace function public.validate_coupon(p_code text, p_subtotal int)
returns jsonb language plpgsql security definer set search_path = public as $$
declare c coupons%rowtype; v_used int; v_discount int;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  if coalesce(trim(p_code),'') = '' then return jsonb_build_object('valid',false,'message','Enter a coupon code.'); end if;
  select * into c from coupons where code = upper(trim(p_code)) and is_active;
  if not found then return jsonb_build_object('valid',false,'message','This coupon is not available.'); end if;
  if c.starts_at is not null and now() < c.starts_at then return jsonb_build_object('valid',false,'message','This coupon is not active yet.'); end if;
  if c.expires_at is not null and now() >= c.expires_at then return jsonb_build_object('valid',false,'message','This coupon has expired.'); end if;
  if c.usage_limit is not null and c.used_count >= c.usage_limit then return jsonb_build_object('valid',false,'message','This coupon has reached its redemption limit.'); end if;
  if coalesce(p_subtotal,0) < c.minimum_order then return jsonb_build_object('valid',false,'message',format('Add items worth ₹%s to use this coupon.',c.minimum_order)); end if;
  select count(*) into v_used from coupon_redemptions where coupon_id=c.id and user_id=auth.uid();
  if v_used >= c.per_user_limit then return jsonb_build_object('valid',false,'message','You have used this coupon the maximum number of times.'); end if;
  v_discount := case when c.discount_type='percent' then floor(p_subtotal*c.discount_value/100.0)::int else c.discount_value end;
  v_discount := least(greatest(0,p_subtotal),coalesce(least(v_discount,c.maximum_discount),v_discount));
  return jsonb_build_object('valid',true,'code',c.code,'description',c.description,'discount_amount',v_discount);
end $$;

drop function if exists public.place_order_with_coupon(jsonb,boolean,text,text,text);
create or replace function public.place_order_with_coupon(
  p_items jsonb,
  p_use_coins boolean,
  p_address text,
  p_phone text,
  p_coupon_code text default null,
  p_customer_name text default null,
  p_distance_km numeric default null
)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  s settings%rowtype; p profiles%rowtype; c coupons%rowtype;
  r record; e record; x record; v record; v_oid bigint;
  v_sub int:=0; v_unit int; v_extra_price int; v_coin_discount int:=0;
  v_coins_used int:=0; v_coupon_discount int:=0; v_total int; v_extra_details jsonb;
  v_delivery_fee int; v_delivery_fee_before_discount int; v_gst_amount int;
  v_user_uses int; v_coupon_code text;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Your cart is empty'; end if;
  select * into s from settings where id=1;
  if not coalesce(s.store_online,true) then raise exception '%',coalesce(s.offline_message,'Ordering is offline right now.'); end if;
  select * into p from profiles where id=auth.uid() for update;
  if coalesce(trim(p_address),'')='' then raise exception 'Delivery address is required'; end if;
  if coalesce(trim(p_phone),'')='' then raise exception 'Phone number is required'; end if;
  if coalesce(trim(p_customer_name),trim(p.name),'')='' then raise exception 'Customer name is required'; end if;
  if p_distance_km is not null and (p_distance_km<0 or p_distance_km>s.max_delivery_km) then
    raise exception 'Delivery is available only within % km',s.max_delivery_km;
  end if;

  insert into orders(
    user_id,address,phone,customer_name,delivery_fee,delivery_fee_before_discount,delivery_distance_km,order_stage
  )
  values(
    auth.uid(),trim(p_address),nullif(trim(p_phone),''),coalesce(nullif(trim(p_customer_name),''),p.name),
    0,0,p_distance_km,'pending'
  ) returning id into v_oid;

  for r in select value from jsonb_array_elements(p_items) loop
    select vr.id as variant_id,vr.item_id,
      case when vr.id=s.offer_variant_id and s.offer_date=today_ist()
        and (s.offer_ends_at is null or s.offer_ends_at>now()) then s.offer_price else vr.price end as price,
      vr.label,i.name,i.brand_id,i.is_available,b.is_open
    into v from item_variants vr join menu_items i on i.id=vr.item_id join brands b on b.id=i.brand_id
    where vr.id=(r.value->>'variant_id')::bigint;
    if not found then raise exception 'A selected menu size no longer exists'; end if;
    if not v.is_available or not v.is_open then raise exception '% is not available right now',v.name; end if;
    v_extra_price:=0; v_extra_details:='[]'::jsonb;
    for e in select value from jsonb_array_elements(coalesce(r.value->'extras','[]'::jsonb)) loop
      select id,name,price into x from item_extras
      where id=(e.value->>'id')::bigint and item_id=v.item_id and is_available;
      if not found then raise exception 'A selected extra is no longer available'; end if;
      v_extra_price:=v_extra_price+x.price;
      v_extra_details:=v_extra_details||jsonb_build_array(jsonb_build_object('id',x.id,'name',x.name,'price',x.price));
    end loop;
    v_unit:=v.price+v_extra_price;
    insert into order_items(order_id,menu_item_id,brand_id,item_name,qty,unit_price,extra_details)
    values(v_oid,v.item_id,v.brand_id,v.name||' ('||v.label||')',greatest(1,least(20,coalesce((r.value->>'qty')::int,1))),v_unit,v_extra_details);
    v_sub:=v_sub+v_unit*greatest(1,least(20,coalesce((r.value->>'qty')::int,1)));
  end loop;
  if v_sub<s.min_order then raise exception 'Minimum order is ₹%',s.min_order; end if;

  v_delivery_fee_before_discount:=coalesce(s.delivery_fee,0)+ceil(
    greatest(0,coalesce(p_distance_km,s.min_delivery_km)-s.min_delivery_km)*coalesce(s.delivery_per_km,0)
  )::int;
  v_delivery_fee:=case
    when coalesce(s.delivery_free,false)
      or (coalesce(s.free_delivery_minimum,0)>0 and v_sub>=s.free_delivery_minimum) then 0
    else v_delivery_fee_before_discount
  end;
  v_gst_amount:=round(v_sub*5.0/105.0)::int;

  update orders set delivery_fee=v_delivery_fee,
    delivery_fee_before_discount=v_delivery_fee_before_discount,gst_amount=v_gst_amount where id=v_oid;

  v_coupon_code:=nullif(upper(trim(coalesce(p_coupon_code,''))),'');
  if v_coupon_code is not null then
    select * into c from coupons where code=v_coupon_code for update;
    if not found or not c.is_active then raise exception 'This coupon is not available'; end if;
    if c.starts_at is not null and now()<c.starts_at then raise exception 'This coupon is not active yet'; end if;
    if c.expires_at is not null and now()>=c.expires_at then raise exception 'This coupon has expired'; end if;
    if c.usage_limit is not null and c.used_count>=c.usage_limit then raise exception 'This coupon has reached its redemption limit'; end if;
    if v_sub<c.minimum_order then raise exception 'Coupon requires a minimum order of ₹%',c.minimum_order; end if;
    select count(*) into v_user_uses from coupon_redemptions where coupon_id=c.id and user_id=auth.uid();
    if v_user_uses>=c.per_user_limit then raise exception 'You have used this coupon the maximum number of times'; end if;
    v_coupon_discount:=case when c.discount_type='percent' then floor(v_sub*c.discount_value/100.0)::int else c.discount_value end;
    v_coupon_discount:=least(v_sub,coalesce(least(v_coupon_discount,c.maximum_discount),v_coupon_discount));
  end if;

  if coalesce(p_use_coins,false) then
    v_coin_discount:=least(p.coins/100,floor(greatest(0,v_sub-v_coupon_discount)*s.max_coin_pct/100.0)::int);
    v_coins_used:=v_coin_discount*100;
    if v_coins_used>0 then update profiles set coins=coins-v_coins_used where id=auth.uid(); end if;
  end if;
  v_total:=greatest(0,v_sub+v_delivery_fee-v_coupon_discount-v_coin_discount);
  update orders set subtotal=v_sub,coupon_code=v_coupon_code,coupon_discount=v_coupon_discount,
    coin_discount=v_coin_discount,coins_used=v_coins_used,total=v_total where id=v_oid;
  if v_coupon_code is not null then
    update coupons set used_count=used_count+1 where id=c.id;
    insert into coupon_redemptions(coupon_id,user_id,order_id,discount_amount)
    values(c.id,auth.uid(),v_oid,v_coupon_discount);
  end if;
  return v_oid;
end $$;

create or replace function public.admin_update_order(
  p_id bigint,p_stage text,p_reason text default null,p_payment_type text default null
)
returns void language plpgsql security definer set search_path = public as $$
declare o orders%rowtype; s settings%rowtype; p profiles%rowtype; d date; n int; v_legacy_status text;
begin
  if not is_admin() then raise exception 'Admins only'; end if;
  select * into o from orders where id=p_id for update;
  if not found then raise exception 'Order not found'; end if;
  if o.order_stage in ('delivered','rejected','cancelled') then raise exception 'Order is already closed'; end if;
  if p_stage='rejected' then
    if o.order_stage<>'pending' then raise exception 'Only pending orders can be rejected'; end if;
    if coalesce(trim(p_reason),'')='' then raise exception 'Enter a reason for rejecting this order'; end if;
  elsif p_stage='accepted' then
    if o.order_stage<>'pending' then raise exception 'Only pending orders can be accepted'; end if;
  elsif p_stage='preparing' then
    if o.order_stage<>'accepted' then raise exception 'Accept the order before preparing it'; end if;
  elsif p_stage='ready' then
    if o.order_stage<>'preparing' then raise exception 'Only preparing orders can be marked ready'; end if;
  elsif p_stage='out_for_delivery' then
    if o.order_stage<>'ready' then raise exception 'Mark the order ready before dispatch'; end if;
  elsif p_stage='payment_received' then
    if o.order_stage<>'out_for_delivery' then raise exception 'Record payment after dispatch'; end if;
    if p_payment_type not in ('cash','upi','card','online','other') then raise exception 'Choose a payment type'; end if;
  elsif p_stage='delivered' then
    if o.order_stage<>'payment_received' then raise exception 'Record payment before marking delivered'; end if;
  elsif p_stage='cancelled' then
    if o.order_stage not in ('pending','accepted','preparing','ready') then raise exception 'This order can no longer be cancelled'; end if;
  else raise exception 'Unsupported order action';
  end if;

  v_legacy_status:=case when p_stage in ('accepted','preparing','ready') then 'preparing'
    when p_stage in ('out_for_delivery','payment_received') then 'out_for_delivery'
    when p_stage in ('delivered') then 'delivered'
    when p_stage in ('rejected','cancelled') then 'cancelled'
    else 'placed' end;
  update orders set order_stage=p_stage,status=v_legacy_status::order_status,
    accepted_at=case when p_stage='accepted' then now() else accepted_at end,
    ready_at=case when p_stage='ready' then now() else ready_at end,
    payment_received_at=case when p_stage='payment_received' then now() else payment_received_at end,
    payment_type=case when p_stage='payment_received' then p_payment_type else payment_type end,
    delivered_at=case when p_stage='delivered' then now() else delivered_at end,
    dispatched_at=case when p_stage='out_for_delivery' then now() else dispatched_at end,
    rejection_reason=case when p_stage='rejected' then trim(p_reason) when p_stage='cancelled' then nullif(trim(p_reason),'') else rejection_reason end
  where id=p_id;

  if p_stage in ('rejected','cancelled') and o.coins_used>0 then
    update profiles set coins=coins+o.coins_used where id=o.user_id;
  end if;
  if p_stage in ('rejected','cancelled') and o.coupon_code is not null then
    update coupons set used_count=greatest(0,used_count-1) where code=o.coupon_code;
    delete from coupon_redemptions where order_id=o.id;
  end if;
  if p_stage='delivered' then
    select * into s from settings where id=1;
    select * into p from profiles where id=o.user_id for update;
    d:=today_ist();
    if p.last_order_date is distinct from d then
      if p.last_order_date is null or d-p.last_order_date>s.streak_break_days then n:=1;
      else n:=p.streak+1; end if;
      update profiles set streak=n,longest_streak=greatest(longest_streak,n),last_order_date=d where id=o.user_id;
      insert into user_rewards(user_id,milestone,gift)
      select o.user_id,milestone,gift from streak_rewards where is_active and milestone=n on conflict do nothing;
    end if;
  end if;
end $$;

create or replace function public.auto_reject_expired_orders()
returns int language plpgsql security definer set search_path = public as $$
declare o orders%rowtype; v_count int:=0;
begin
  for o in select * from orders where order_stage='pending' and created_at<=now()-interval '5 minutes' for update skip locked loop
    update orders set order_stage='rejected',status='cancelled',rejection_reason='No response within 5 minutes'
    where id=o.id and order_stage='pending';
    if o.coins_used>0 then update profiles set coins=coins+o.coins_used where id=o.user_id; end if;
    if o.coupon_code is not null then
      update coupons set used_count=greatest(0,used_count-1) where code=o.coupon_code;
      delete from coupon_redemptions where order_id=o.id;
    end if;
    v_count:=v_count+1;
  end loop;
  return v_count;
end $$;

create or replace function public.admin_delete_outlet(p_id text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not is_admin() then raise exception 'Admins only'; end if;
  if not exists(select 1 from brands where id=p_id) then raise exception 'Outlet not found'; end if;
  update settings set offer_variant_id=null,offer_price=null,offer_date=null,offer_ends_at=null
  where offer_variant_id in (select v.id from item_variants v join menu_items i on i.id=v.item_id where i.brand_id=p_id);
  delete from menu_items where brand_id=p_id;
  delete from brands where id=p_id;
end $$;

revoke all on function public.validate_coupon(text,int) from public,anon;
revoke all on function public.customer_available_coupons() from public,anon;
revoke all on function public.place_order_with_coupon(jsonb,boolean,text,text,text,text,numeric) from public,anon;
revoke all on function public.admin_update_order(bigint,text,text,text) from public,anon;
revoke all on function public.auto_reject_expired_orders() from public,anon,authenticated;
revoke all on function public.admin_delete_outlet(text) from public,anon;
revoke all on function public.set_order_status(bigint,order_status) from public,anon,authenticated;
grant execute on function public.validate_coupon(text,int) to authenticated;
grant execute on function public.customer_available_coupons() to authenticated;
grant execute on function public.place_order_with_coupon(jsonb,boolean,text,text,text,text,numeric) to authenticated;
grant execute on function public.admin_update_order(bigint,text,text,text) to authenticated;
grant execute on function public.admin_delete_outlet(text) to authenticated;
revoke all on function public.place_order(jsonb,boolean,text,text) from public,anon,authenticated;

-- Run the expiry check once each minute. Supabase Cron uses pg_cron.
create extension if not exists pg_cron with schema pg_catalog;
do $$ declare j record; begin
  for j in select jobid from cron.job where jobname='eat60-reject-pending-orders' loop
    perform cron.unschedule(j.jobid);
  end loop;
  perform cron.schedule('eat60-reject-pending-orders','* * * * *','select public.auto_reject_expired_orders();');
end $$;

-- Menu photos are uploaded to this public-read, admin-write bucket.
insert into storage.buckets(id,name,public)
values('menu-images','menu-images',true) on conflict(id) do update set public=true;
drop policy if exists "EAT60 menu photos public read" on storage.objects;
create policy "EAT60 menu photos public read" on storage.objects for select using(bucket_id='menu-images');
drop policy if exists "EAT60 admin menu photos insert" on storage.objects;
create policy "EAT60 admin menu photos insert" on storage.objects for insert to authenticated with check(bucket_id='menu-images' and public.is_admin());
drop policy if exists "EAT60 admin menu photos update" on storage.objects;
create policy "EAT60 admin menu photos update" on storage.objects for update to authenticated using(bucket_id='menu-images' and public.is_admin()) with check(bucket_id='menu-images' and public.is_admin());
drop policy if exists "EAT60 admin menu photos delete" on storage.objects;
create policy "EAT60 admin menu photos delete" on storage.objects for delete to authenticated using(bucket_id='menu-images' and public.is_admin());

-- Feed comments can be answered by the official EAT60 account. Replies remain normal
-- comments, linked to the customer comment so both admin and customer can follow them.
alter table public.comments add column if not exists parent_comment_id bigint references public.comments(id) on delete cascade;
create index if not exists comments_parent_idx on public.comments(parent_comment_id,created_at);
drop policy if exists "own react read" on public.reactions;
create policy "own react read" on public.reactions for select using (user_id=auth.uid() or public.is_admin());
create or replace view public.feed_comments as
  select c.id,c.post_id,c.body,c.created_at,p.name as author,c.parent_comment_id,(p.role='admin') as is_admin
  from public.comments c join public.profiles p on p.id=c.user_id;
grant select on public.feed_comments to anon,authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='comments') then
    alter publication supabase_realtime add table public.comments;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='reactions') then
    alter publication supabase_realtime add table public.reactions;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='feed_posts') then
    alter publication supabase_realtime add table public.feed_posts;
  end if;
end $$;

notify pgrst,'reload schema';
