-- EAT60 by Foodverse Kitchen: Supabase setup
-- Run once in Supabase > SQL Editor on a NEW project (it creates everything).
-- Money, coins, streaks and game rewards are all calculated here on the server,
-- so customers cannot cheat by editing the app.

-- ========== 1. TABLES ==========
create type order_status as enum ('placed','preparing','out_for_delivery','delivered','cancelled');

create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'Player',
  username text not null unique check (username ~ '^[a-z0-9_]{3,24}$'),
  gender text not null default 'other' check (gender in ('male','female','other')),
  avatar_id smallint not null default 1 check (avatar_id between 1 and 10),
  phone text,
  address text,
  area text,
  city text,
  role text not null default 'customer' check (role in ('customer','admin')),
  coins int not null default 0 check (coins >= 0),
  xp int not null default 0,
  streak int not null default 0,
  longest_streak int not null default 0,
  last_order_date date,
  created_at timestamptz not null default now()
);

create table brands (
  id text primary key,
  name text not null,
  emoji text,
  is_open boolean not null default true,
  about_category text not null default '',
  about_tagline text not null default '',
  zomato_url text not null default '',
  swiggy_url text not null default ''
);

create table menu_items (
  id bigint generated by default as identity primary key,
  brand_id text not null references brands(id),
  category text not null,
  name text not null,
  description text,
  image_url text,
  is_available boolean not null default true
);

create table item_variants (
  id bigint generated always as identity primary key,
  item_id bigint not null references menu_items(id) on delete cascade,
  label text not null,
  price int not null check (price > 0)
);

create table settings (
  id int primary key default 1 check (id = 1),
  delivery_fee int not null default 20,
  min_order int not null default 99,
  min_delivery_km numeric(6,2) not null default 2,
  delivery_per_km int not null default 5,
  free_delivery_minimum int not null default 0,
  delivery_free boolean not null default false,
  max_delivery_km numeric(6,2) not null default 5,
  max_coin_pct int not null default 20,      -- coins can pay at most this % of the items total
  daily_coin_cap int not null default 125,   -- max coins a player can earn from games per day
  streak_break_days int not null default 30, -- streak resets after this many days with no order
  tiffin_url text,
  about_founder_name text not null default '',
  about_founder_photo_url text not null default '',
  about_founder_instagram_url text not null default '',
  about_founder_portfolio_url text not null default '',
  about_outlet_links jsonb not null default '{}'::jsonb,
  social_links jsonb not null default '{}'::jsonb,
  home_ad_image_url text not null default '',
  home_ad_link text not null default '',
  home_ad_alt text not null default '',
  home_ad_active boolean not null default false,
  home_ad_starts_at timestamptz,
  home_ad_ends_at timestamptz,
  offer_variant_id bigint references item_variants(id),
  offer_price int,
  offer_date date,                           -- offer of the day is valid only on this date
  offer_title text not null default 'OFFER OF THE DAY',
  offer_message text not null default 'GRAB THIS OFFER BEFORE IT ENDS',
  offer_ends_at timestamptz
);

create table streak_rewards (
  milestone int primary key,
  gift text not null,
  is_active boolean not null default true,
  coin_reward int not null default 0 check (coin_reward >= 0),
  coupon_code text
);

create table user_rewards (
  id bigint generated always as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  milestone int not null,
  gift text not null,
  coin_reward int not null default 0 check (coin_reward >= 0),
  coupon_code text,
  claimed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, milestone)
);

create table referral_codes (
  user_id uuid primary key references profiles(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table referral_signups (
  referred_user uuid primary key references profiles(id) on delete cascade,
  referrer_user uuid not null references profiles(id) on delete cascade,
  signup_code text not null,
  new_user_claimed boolean not null default false,
  referrer_claimed boolean not null default false,
  created_at timestamptz not null default now(),
  new_user_claimed_at timestamptz,
  referrer_claimed_at timestamptz,
  constraint referral_signups_not_self check (referred_user <> referrer_user)
);

create table orders (
  id bigint generated always as identity (start with 1001) primary key,
  user_id uuid not null references profiles(id),
  status order_status not null default 'placed',
  address text,
  phone text,
  customer_name text,
  subtotal int not null default 0,
  delivery_fee int not null default 0,
  delivery_fee_before_discount int not null default 0,
  delivery_distance_km numeric(6,2),
  prep_time_minutes int not null default 15 check (prep_time_minutes between 15 and 180),
  gst_amount int not null default 0,
  coin_discount int not null default 0,
  coins_used int not null default 0,
  total int not null default 0,
  created_at timestamptz not null default now(),
  delivered_at timestamptz
);

create table order_items (
  id bigint generated always as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  menu_item_id bigint references menu_items(id) on delete set null,
  brand_id text,
  item_name text not null,
  qty int not null,
  unit_price int not null
);

create table order_reviews (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references orders(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  feedback text check (feedback is null or char_length(feedback) <= 500),
  created_at timestamptz not null default now()
);

create table feed_posts (
  id bigint generated always as identity primary key,
  kind text not null check (kind in ('news','poll')),
  body text not null,
  image_url text,
  created_at timestamptz not null default now()
);

create table poll_options (
  id bigint generated always as identity primary key,
  post_id bigint not null references feed_posts(id) on delete cascade,
  label text not null
);

create table poll_votes (
  post_id bigint not null references feed_posts(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  option_id bigint not null references poll_options(id) on delete cascade,
  primary key (post_id, user_id)
);

create table reactions (
  post_id bigint not null references feed_posts(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  emoji text not null check (emoji in ('🔥','😋','👍','❤️')),
  primary key (post_id, user_id, emoji)
);

create table feed_views (
  post_id bigint not null references feed_posts(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table comments (
  id bigint generated always as identity primary key,
  post_id bigint not null references feed_posts(id) on delete cascade,
  user_id uuid not null references profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 300),
  created_at timestamptz not null default now()
);

create table game_scores (
  id bigint generated always as identity primary key,
  user_id uuid not null references profiles(id) on delete cascade,
  game text not null check (game in ('snake','burger','qmaths')),
  score int not null,
  duration_ms int not null,
  xp int not null,
  coins int not null,
  played_at timestamptz not null default now()
);

create table game_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  game text not null check (game in ('snake','burger','qmaths')),
  started_at timestamptz not null default now(),
  expires_at timestamptz not null,
  completed_at timestamptz
);
create index game_sessions_user_started_idx on game_sessions(user_id, started_at desc);

create table weekly_game_rewards (
  week_start date not null,
  user_id uuid not null references profiles(id) on delete cascade,
  rank int not null check (rank between 1 and 10),
  coins int not null check (coins > 0),
  awarded_at timestamptz not null default now(),
  primary key (week_start, user_id),
  unique (week_start, rank)
);


-- ========== 2. HELPERS ==========
create function today_ist() returns date language sql stable as
$$ select (now() at time zone 'Asia/Kolkata')::date $$;

create function is_admin() returns boolean language sql stable security definer set search_path = public as
$$ select exists (select 1 from profiles where id = auth.uid() and role = 'admin') $$;
revoke all on function is_admin() from public;
grant execute on function is_admin() to anon, authenticated;

-- Create a profile automatically when someone signs up
create function handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
declare v_base text; v_referral_code text; v_referrer uuid;
begin
  v_base := left(regexp_replace(lower(split_part(coalesce(new.email, 'player'), '@', 1)), '[^a-z0-9_]+', '_', 'g'), 13);
  insert into profiles (id, name, username)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1), 'Player'),
    coalesce(nullif(v_base, ''), 'player') || '_' || substr(replace(new.id::text, '-', ''), 1, 10)
  );
  insert into referral_codes (user_id, code)
  values (new.id, 'EAT-' || upper(substr(replace(new.id::text, '-', ''), 1, 12)))
  on conflict (user_id) do nothing;
  v_referral_code := upper(trim(coalesce(new.raw_user_meta_data->>'referral_code', '')));
  if v_referral_code <> '' then
    select user_id into v_referrer from referral_codes where code = v_referral_code;
    if v_referrer is not null and v_referrer <> new.id then
      insert into referral_signups (referred_user, referrer_user, signup_code)
      values (new.id, v_referrer, v_referral_code)
      on conflict (referred_user) do nothing;
    end if;
  end if;
  return new;
end $$;

create function customer_referral_dashboard()
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare v_user uuid := auth.uid(); v_code text; v_invites jsonb; v_pending_coins integer;
  v_can_redeem boolean; v_can_claim boolean;
begin
  if v_user is null then raise exception 'Please log in first'; end if;
  select code into v_code from referral_codes where user_id = v_user;
  select coalesce(jsonb_agg(jsonb_build_object(
    'username', p.username, 'joined_at', r.created_at,
    'claimed', r.new_user_claimed, 'referrer_reward_claimed', r.referrer_claimed
  ) order by r.created_at desc), '[]'::jsonb)
  into v_invites from referral_signups r join profiles p on p.id = r.referred_user
  where r.referrer_user = v_user;
  select count(*)::integer * 3000 into v_pending_coins from referral_signups
  where referrer_user = v_user and new_user_claimed and not referrer_claimed;
  select exists(select 1 from referral_signups where referred_user = v_user and not new_user_claimed)
    and not exists(select 1 from orders o where o.user_id = v_user)
  into v_can_claim;
  select not exists(select 1 from referral_signups where referred_user = v_user)
    and not exists(select 1 from orders o where o.user_id = v_user)
  into v_can_redeem from profiles p where p.id = v_user;
  return jsonb_build_object('code', v_code, 'invites', v_invites,
    'pending_referrer_coins', coalesce(v_pending_coins, 0),
    'can_claim_new_user', coalesce(v_can_claim, false),
    'can_redeem_code', coalesce(v_can_redeem, false));
end $$;

create function claim_referral_reward(p_code text default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user uuid := auth.uid(); v_referrer uuid; v_signup referral_signups%rowtype;
  v_code text := upper(trim(coalesce(p_code, ''))); v_created_at timestamptz;
begin
  if v_user is null then raise exception 'Please log in first'; end if;
  if exists(select 1 from orders where user_id = v_user) then
    raise exception 'Referral rewards must be claimed before your first order';
  end if;
  select * into v_signup from referral_signups where referred_user = v_user for update;
  if not found then
    if v_code = '' then raise exception 'Enter a referral code to continue'; end if;
    select created_at into v_created_at from profiles where id = v_user for update;
    if v_created_at is null or exists(select 1 from orders where user_id = v_user) then
      raise exception 'Referral codes are available to new customers only';
    end if;
    select user_id into v_referrer from referral_codes where code = v_code;
    if v_referrer is null then raise exception 'That referral code is not valid'; end if;
    if v_referrer = v_user then raise exception 'You cannot redeem your own referral code'; end if;
    insert into referral_signups (referred_user, referrer_user, signup_code)
    values (v_user, v_referrer, v_code) on conflict (referred_user) do nothing;
    select * into v_signup from referral_signups where referred_user = v_user for update;
  end if;
  if v_signup.new_user_claimed then raise exception 'Your referral reward has already been claimed'; end if;
  update referral_signups set new_user_claimed = true, new_user_claimed_at = now()
  where referred_user = v_user and not new_user_claimed;
  if not found then raise exception 'Your referral reward has already been claimed'; end if;
  update profiles set coins = coins + 2500 where id = v_user;
  return jsonb_build_object('coins_awarded', 2500, 'referrer_reward', 3000);
end $$;

create function claim_referral_bonus()
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user uuid := auth.uid(); v_invites integer; v_coins integer;
begin
  if v_user is null then raise exception 'Please log in first'; end if;
  update referral_signups set referrer_claimed = true, referrer_claimed_at = now()
  where referrer_user = v_user and new_user_claimed and not referrer_claimed;
  get diagnostics v_invites = row_count;
  v_coins := v_invites * 3000;
  if v_coins > 0 then update profiles set coins = coins + v_coins where id = v_user; end if;
  return jsonb_build_object('coins_awarded', v_coins, 'invites_claimed', v_invites);
end $$;

-- A customer can claim each reached streak reward once; admins can fulfill the gift in person.
create function claim_streak_reward(p_milestone int)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_gift text; v_coin_reward int; v_coupon_code text; v_coins_awarded int := 0; v_best int;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  select gift, coin_reward, coupon_code into v_gift, v_coin_reward, v_coupon_code from streak_rewards
  where milestone = p_milestone and is_active for update;
  if v_gift is null then raise exception 'That streak reward does not exist'; end if;
  select greatest(coalesce(longest_streak, 0), coalesce(streak, 0)) into v_best from profiles where id = auth.uid();
  if coalesce(v_best, 0) < p_milestone then raise exception 'Keep your order streak going to unlock this reward'; end if;
  insert into user_rewards (user_id, milestone, gift, coin_reward, coupon_code)
  values (auth.uid(), p_milestone, v_gift, v_coin_reward, v_coupon_code)
  on conflict (user_id, milestone) do nothing;
  update user_rewards set claimed = true, gift = v_gift, coin_reward = v_coin_reward, coupon_code = v_coupon_code
  where user_id = auth.uid() and milestone = p_milestone
    and (claimed = false or (coin_reward = 0 and v_coin_reward > 0))
  returning coin_reward into v_coins_awarded;
  if found and v_coins_awarded > 0 then
    update profiles set coins = coins + v_coins_awarded where id = auth.uid();
  else
    v_coins_awarded := 0;
  end if;
  return jsonb_build_object('milestone', p_milestone, 'gift', v_gift, 'claimed', true, 'coins_awarded', v_coins_awarded, 'coupon_code', v_coupon_code);
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function handle_new_user();

-- ========== 3. SECURITY (Row Level Security) ==========
alter table profiles enable row level security;
alter table brands enable row level security;
alter table menu_items enable row level security;
alter table item_variants enable row level security;
alter table settings enable row level security;
alter table streak_rewards enable row level security;
alter table user_rewards enable row level security;
alter table referral_codes enable row level security;
alter table referral_signups enable row level security;
revoke all on referral_codes, referral_signups from anon, authenticated;
grant select on referral_signups to authenticated;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table feed_posts enable row level security;
alter table poll_options enable row level security;
alter table poll_votes enable row level security;
alter table reactions enable row level security;
alter table feed_views enable row level security;
alter table comments enable row level security;
alter table game_scores enable row level security;
alter table game_sessions enable row level security;
alter table weekly_game_rewards enable row level security;
alter table order_reviews enable row level security;

-- Customers can change only their own name and phone, never coins, xp, streak or role
revoke update on profiles from anon, authenticated;
grant update (name, username, phone, address, area, city, gender, avatar_id) on profiles to authenticated;
create policy "profile read" on profiles for select using (id = auth.uid() or is_admin());
create policy "profile edit" on profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "referral signup parties can view" on referral_signups for select to authenticated
  using (referred_user = auth.uid() or referrer_user = auth.uid());

-- Public read, admin write
create policy "read" on brands for select using (true);
create policy "admin" on brands for all using (is_admin()) with check (is_admin());
create policy "read" on menu_items for select using (true);
create policy "admin" on menu_items for all using (is_admin()) with check (is_admin());
create policy "read" on item_variants for select using (true);
create policy "admin" on item_variants for all using (is_admin()) with check (is_admin());
create policy "read" on settings for select using (true);
create policy "admin" on settings for all using (is_admin()) with check (is_admin());
create policy "read" on streak_rewards for select using (true);
create policy "admin" on streak_rewards for all using (is_admin()) with check (is_admin());
create policy "read" on feed_posts for select using (true);
create policy "admin" on feed_posts for all using (is_admin()) with check (is_admin());
create policy "read" on poll_options for select using (true);
create policy "admin" on poll_options for all using (is_admin()) with check (is_admin());

-- Orders: customers see only their own. They are created and updated only by the functions below.
create policy "own or admin" on orders for select using (user_id = auth.uid() or is_admin());
create policy "own or admin" on order_items for select using (
  exists (select 1 from orders o where o.id = order_id and (o.user_id = auth.uid() or is_admin())));

revoke all on order_reviews from anon, authenticated;
grant select, insert on order_reviews to authenticated;
create policy "own order review read" on order_reviews for select using (user_id = auth.uid());
create policy "review own delivered order" on order_reviews for insert with check (
  user_id = auth.uid()
  and exists (
    select 1 from orders o
    where o.id = order_id and o.user_id = auth.uid() and o.status::text = 'delivered'
  )
);

create policy "own or admin" on user_rewards for select using (user_id = auth.uid() or is_admin());
create policy "admin" on user_rewards for update using (is_admin()) with check (is_admin());

-- Feed interaction
create policy "own vote read" on poll_votes for select using (user_id = auth.uid());
create policy "vote" on poll_votes for insert with check (
  user_id = auth.uid()
  and exists (select 1 from poll_options o where o.id = option_id and o.post_id = poll_votes.post_id));
create policy "own react read" on reactions for select using (user_id = auth.uid());
create policy "react" on reactions for insert with check (user_id = auth.uid());
create policy "unreact" on reactions for delete using (user_id = auth.uid());
create policy "own feed view read" on feed_views for select using (user_id = auth.uid());
create policy "record own feed view" on feed_views for insert with check (user_id = auth.uid());
create policy "read" on comments for select using (true);
create policy "comment" on comments for insert with check (user_id = auth.uid());
create policy "delete own or admin" on comments for delete using (user_id = auth.uid() or is_admin());

create policy "own scores" on game_scores for select using (user_id = auth.uid() or is_admin());
revoke all on game_sessions, weekly_game_rewards from public, anon, authenticated;

-- Public summary views (counts only, no user ids). They run with owner rights on purpose.
create view poll_results as
  select post_id, option_id, count(*)::int as votes from poll_votes group by post_id, option_id;
create view reaction_counts as
  select post_id, emoji, count(*)::int as total from reactions group by post_id, emoji;
create view feed_view_counts as
  select post_id, count(*)::int as total from feed_views group by post_id;
create view feed_comments as
  select c.id, c.post_id, c.body, c.created_at, p.name as author
  from comments c join profiles p on p.id = c.user_id;
create view menu_item_ratings as
  select oi.menu_item_id, round(avg(r.rating)::numeric, 1) as average_rating,
         count(distinct r.id)::int as review_count
  from order_items oi join order_reviews r on r.order_id = oi.order_id
  where oi.menu_item_id is not null
  group by oi.menu_item_id;
grant select on poll_results, reaction_counts, feed_view_counts, feed_comments, menu_item_ratings to anon, authenticated;

-- ========== 4. SERVER-SIDE LOGIC ==========

-- Place an order. The app sends only variant ids and quantities; prices come from the database.
-- p_items example: [{"variant_id": 3, "qty": 2}]
create function place_order(p_items jsonb, p_use_coins boolean, p_address text, p_phone text)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  s settings%rowtype; p profiles%rowtype; r record; v record;
  v_sub int := 0; v_price int; v_disc int := 0; v_coins int := 0; v_oid bigint;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  select * into s from settings where id = 1;
  select * into p from profiles where id = auth.uid() for update;
  if coalesce(trim(p_address), '') = '' then raise exception 'Delivery address is required'; end if;

  insert into orders (user_id, address, phone, delivery_fee)
  values (auth.uid(), p_address, p_phone, s.delivery_fee) returning id into v_oid;

  for r in
    select (e->>'variant_id')::bigint as vid,
           greatest(1, least(20, coalesce((e->>'qty')::int, 1))) as q
    from jsonb_array_elements(p_items) e
  loop
    select vr.price, vr.label, i.name, i.brand_id, i.is_available, b.is_open into v
    from item_variants vr
    join menu_items i on i.id = vr.item_id
    join brands b on b.id = i.brand_id
    where vr.id = r.vid;
    if not found then raise exception 'Item not found'; end if;
    if not v.is_available or not v.is_open then raise exception '% is not available right now', v.name; end if;

    v_price := v.price;
    if r.vid = s.offer_variant_id and s.offer_date = today_ist()
      and (s.offer_ends_at is null or s.offer_ends_at > now()) then v_price := s.offer_price; end if;

    insert into order_items (order_id, menu_item_id, brand_id, item_name, qty, unit_price)
    values (v_oid, v.item_id, v.brand_id, v.name || ' (' || v.label || ')', r.q, v_price);
    v_sub := v_sub + v_price * r.q;
  end loop;

  if v_sub = 0 then raise exception 'Your cart is empty'; end if;
  if v_sub < s.min_order then raise exception 'Minimum order is Rs %', s.min_order; end if;

  if p_use_coins then
    v_disc  := least(p.coins / 100, floor(v_sub * s.max_coin_pct / 100.0)::int);  -- 100 coins = Rs 1
    v_coins := v_disc * 100;
    update profiles set coins = coins - v_coins where id = auth.uid();
  end if;

  update orders set subtotal = v_sub, coin_discount = v_disc, coins_used = v_coins,
         total = v_sub + s.delivery_fee - v_disc
  where id = v_oid;
  return v_oid;
end $$;

-- Admin changes order status. On "delivered" the customer's streak is updated.
create function set_order_status(p_id bigint, p_status order_status)
returns void language plpgsql security definer set search_path = public as $$
declare o orders%rowtype; s settings%rowtype; p profiles%rowtype; d date; n int;
begin
  if not is_admin() then raise exception 'Admins only'; end if;
  select * into o from orders where id = p_id for update;
  if not found then raise exception 'Order not found'; end if;
  if o.status in ('delivered','cancelled') then raise exception 'Order is already closed'; end if;

  if p_status = 'cancelled' then
    update profiles set coins = coins + o.coins_used where id = o.user_id;   -- refund coins
  end if;
  update orders set status = p_status,
         delivered_at = case when p_status = 'delivered' then now() else delivered_at end
  where id = p_id;

  if p_status = 'delivered' then
    select * into s from settings where id = 1;
    select * into p from profiles where id = o.user_id for update;
    d := today_ist();
    if p.last_order_date is distinct from d then               -- one streak day per calendar day
      if p.last_order_date is null or d - p.last_order_date > s.streak_break_days then n := 1;
      else n := p.streak + 1; end if;
      update profiles set streak = n, longest_streak = greatest(longest_streak, n), last_order_date = d
      where id = o.user_id;
      insert into user_rewards (user_id, milestone, gift)
      select o.user_id, milestone, gift from streak_rewards where milestone = n
      on conflict do nothing;                                    -- each gift is given once per customer
    end if;
  end if;
end $$;

-- Game starts and completion durations are recorded by the server.
create function start_game_session(p_game text)
returns uuid language plpgsql security definer set search_path = public as $$
declare v_session_id uuid;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  if p_game not in ('snake','burger','qmaths') then raise exception 'Invalid game'; end if;
  perform 1 from profiles where id = auth.uid() for update;
  if not found then raise exception 'Player profile not found'; end if;
  if exists (select 1 from game_sessions where user_id = auth.uid() and started_at > now() - interval '5 seconds') then
    raise exception 'Slow down a little';
  end if;
  insert into game_sessions (user_id, game, started_at, expires_at)
  values (
    auth.uid(), p_game, now() + interval '5 seconds',
    now() + interval '5 seconds' + case p_game when 'snake' then interval '10 minutes' when 'burger' then interval '10 minutes' else interval '140 seconds' end
  )
  returning id into v_session_id;
  return v_session_id;
end $$;

create function submit_game_score(p_session_id uuid, p_score int)
returns json language plpgsql security definer set search_path = public as $$
declare s settings%rowtype; p profiles%rowtype; v_session game_sessions%rowtype;
        v_xp int; v_coins int; v_today int; v_max int; v_target_score int; v_duration_ms int;
begin
  if auth.uid() is null then raise exception 'Please log in first'; end if;
  if p_session_id is null or p_score is null or p_score < 0 then raise exception 'Invalid score'; end if;
  select * into v_session from game_sessions where id = p_session_id and user_id = auth.uid() for update;
  if not found or v_session.completed_at is not null then raise exception 'Game session is invalid or already used'; end if;
  if now() > v_session.expires_at then raise exception 'Game session expired'; end if;
  v_duration_ms := floor(extract(epoch from (now() - v_session.started_at)) * 1000)::int;
  if (v_session.game = 'qmaths' and v_duration_ms < 115000)
    or (v_session.game <> 'qmaths' and v_duration_ms < 2000) then
    raise exception 'Game session ended too early';
  end if;
  v_max := case v_session.game
    when 'snake' then (v_duration_ms / 140) * 10
    when 'burger' then (v_duration_ms / 1200) * 10
    else v_duration_ms / 600
  end;
  if p_score > v_max then raise exception 'Invalid score'; end if;

  select * into p from profiles where id = auth.uid() for update;
  select * into s from settings where id = 1;
  select coalesce(sum(coins), 0) into v_today from game_scores
  where user_id = auth.uid() and (played_at at time zone 'Asia/Kolkata')::date = today_ist();
  -- Snake and Burger store 10 points per food or pipe; Maths stores answers.
  v_target_score := case v_session.game when 'snake' then 300 when 'burger' then 200 else 15 end;
  v_xp := 10 + round(50 * least(p_score::numeric / v_target_score, 1))::integer;
  v_coins := greatest(0, least(p_score, s.daily_coin_cap - v_today));

  update game_sessions set completed_at = now() where id = v_session.id;
  insert into game_scores (user_id, game, score, duration_ms, xp, coins)
  values (auth.uid(), v_session.game, p_score, v_duration_ms, v_xp, v_coins);
  update profiles set xp = xp + v_xp, coins = coins + v_coins where id = auth.uid();
  return json_build_object('xp', v_xp, 'coins', v_coins, 'duration_ms', v_duration_ms);
end $$;

revoke all on function start_game_session(text) from public, anon;
revoke all on function submit_game_score(uuid, int) from public, anon;
grant execute on function start_game_session(text) to authenticated;
grant execute on function submit_game_score(uuid, int) to authenticated;

-- Weekly leaderboard counts each player's three highest-XP plays per IST day.
create function get_leaderboard()
returns table (rank bigint, previous_rank bigint, name text, xp bigint, is_me boolean)
language sql stable security definer set search_path = public as $$
  with week_bounds as (
    select date_trunc('week', now() at time zone 'Asia/Kolkata') at time zone 'Asia/Kolkata' as this_week,
           (date_trunc('week', now() at time zone 'Asia/Kolkata') - interval '7 days') at time zone 'Asia/Kolkata' as last_week
  ), ranked_plays as (
    select g.user_id, g.xp, g.played_at, g.id,
      row_number() over (
        partition by g.user_id, (g.played_at at time zone 'Asia/Kolkata')::date
        order by g.xp desc, g.played_at, g.id
      ) as daily_play
    from game_scores g
  ), current_scores as (
    select g.user_id, p.name, sum(g.xp)::bigint as xp
    from ranked_plays g join profiles p on p.id = g.user_id cross join week_bounds w
    where g.played_at >= w.this_week and g.daily_play <= 3
    group by g.user_id, p.name
  ), previous_scores as (
    select g.user_id, row_number() over (order by sum(g.xp) desc, g.user_id) as previous_rank
    from ranked_plays g cross join week_bounds w
    where g.played_at >= w.last_week and g.played_at < w.this_week and g.daily_play <= 3
    group by g.user_id
  )
  select rank() over (order by c.xp desc, c.user_id), ps.previous_rank, c.name, c.xp, (c.user_id = auth.uid())
  from current_scores c left join previous_scores ps on ps.user_id = c.user_id
  order by 1 limit 20 $$;

create function settle_weekly_game_rewards()
returns integer language plpgsql security definer set search_path = public as $$
declare v_week_start date; v_previous_week date; v_awarded integer;
begin
  v_week_start := date_trunc('week', now() at time zone 'Asia/Kolkata')::date;
  v_previous_week := v_week_start - 7;
  with week_bounds as (
    select v_previous_week::timestamp at time zone 'Asia/Kolkata' as week_start,
           v_week_start::timestamp at time zone 'Asia/Kolkata' as week_end
  ), ranked_plays as (
    select g.user_id, g.xp, g.played_at, g.id,
      row_number() over (
        partition by g.user_id, (g.played_at at time zone 'Asia/Kolkata')::date
        order by g.xp desc, g.played_at, g.id
      ) as daily_play
    from game_scores g cross join week_bounds w
    where g.played_at >= w.week_start and g.played_at < w.week_end
  ), totals as (
    select user_id, sum(xp)::integer as total_xp
    from ranked_plays where daily_play <= 3 group by user_id
  ), winners as (
    select user_id, row_number() over (order by total_xp desc, user_id)::integer as place, total_xp
    from totals
  ), inserted as (
    insert into weekly_game_rewards(week_start, user_id, rank, coins)
    select v_previous_week, user_id, place,
      case place when 1 then 500 when 2 then 300 when 3 then 200 else 100 end
    from winners where place <= 10
    on conflict (week_start, user_id) do nothing
    returning user_id, coins
  )
  update profiles p set coins = p.coins + i.coins
  from inserted i where p.id = i.user_id;
  get diagnostics v_awarded = row_count;
  return v_awarded;
end $$;

-- Only logged-in users may call these
revoke all on function place_order(jsonb, boolean, text, text) from public, anon;
revoke all on function set_order_status(bigint, order_status) from public, anon;
revoke all on function get_leaderboard() from public, anon;
revoke all on function settle_weekly_game_rewards() from public, anon, authenticated;
revoke all on function claim_streak_reward(int) from public, anon;
revoke all on function customer_referral_dashboard() from public, anon;
revoke all on function claim_referral_reward(text) from public, anon;
revoke all on function claim_referral_bonus() from public, anon;
grant execute on function place_order(jsonb, boolean, text, text) to authenticated;
grant execute on function set_order_status(bigint, order_status) to authenticated;
grant execute on function get_leaderboard() to authenticated;
grant execute on function claim_streak_reward(int) to authenticated;
grant execute on function customer_referral_dashboard() to authenticated;
grant execute on function claim_referral_reward(text) to authenticated;
grant execute on function claim_referral_bonus() to authenticated;

create extension if not exists pg_cron with schema pg_catalog;
do $$
declare v_job record;
begin
  for v_job in select jobid from cron.job where jobname = 'eat60-weekly-game-rewards' loop
    perform cron.unschedule(v_job.jobid);
  end loop;
  perform cron.schedule('eat60-weekly-game-rewards', '35 18 * * 0', 'select public.settle_weekly_game_rewards();');
end $$;

-- Admin screen gets new orders live
alter publication supabase_realtime add table orders;

-- ========== 5. STARTER DATA (edit later in the admin panel) ==========
insert into brands (id, name, emoji) values
  ('pg','The Pizza Galaxy','🍕'), ('ro','The Red Oven','🔥'), ('ct','Cheesy Town','🍔'),
  ('ws','Wok Story','🥡'), ('wr','Wrap n Roll','🌯');
update brands set about_category='Pizza',about_tagline='Out-of-this-world cheese.' where id='pg';
update brands set about_category='Pizza',about_tagline='Hot, fresh and always glowing.' where id='ro';
update brands set about_category='Burgers, sandwiches, Maggie',about_tagline='The town where cheese is the mayor.' where id='ct';
update brands set about_category='Chinese',about_tagline='Every wok has a tale to toss.' where id='ws';
update brands set about_category='Wraps and kathi rolls',about_tagline='Roll up, roll in.' where id='wr';

insert into menu_items (id, brand_id, category, name, description) values
  (1,'pg','Pizza','Margherita','Cheese, tomato, basil'),
  (2,'pg','Pizza','Tandoori Paneer Pizza','Capsicum, onion, red paprika, paneer in tandoori sauce'),
  (3,'ro','Pizza','Farmhouse Pizza','Mushroom, olives, corn, capsicum'),
  (4,'ct','Burger','Aloo Tikki Burger','Crispy tikki, mayo, onion'),
  (5,'ct','Sandwich','Grilled Veg Sandwich','Veggies and cheese, grilled'),
  (6,'ct','Maggie','Masala Maggie','Classic masala noodles'),
  (7,'ws','Chinese','Veg Hakka Noodles','Wok tossed with sauces'),
  (8,'ws','Chinese','Veg Manchurian','Gravy or dry'),
  (9,'wr','Wraps','Paneer Kathi Roll','Paneer, onion, mint chutney'),
  (10,'wr','Wraps','Veg Cheese Wrap','Veggies, cheese, sauce');
select setval(pg_get_serial_sequence('menu_items','id'), 100);

insert into item_variants (item_id, label, price) values
  (1,'Small 7"',99),(1,'Medium 9"',199),(1,'Large 11"',329),
  (2,'Small 7"',170),(2,'Medium 9"',310),(2,'Large 11"',510),
  (3,'Medium 9"',249),(3,'Large 11"',399),
  (4,'Regular',69),(4,'Double',109),
  (5,'Regular',79),
  (6,'Regular',49),(6,'Cheese',69),
  (7,'Half',89),(7,'Full',149),
  (8,'Half',99),(8,'Full',169),
  (9,'Regular',99),
  (10,'Regular',89);

insert into settings (id) values (1);
-- Offer of the day: Margherita small at Rs 70. Set offer_date to today's date each day (or automate it later).
update settings set offer_variant_id = 1, offer_price = 70, offer_date = today_ist() where id = 1;

insert into streak_rewards (milestone, gift) values
  (10,'Free burger'),(30,'Free pizza'),(50,'Free wrap'),(75,'T-shirt'),(100,'Hoodie'),
  (150,'Free pizza'),(200,'Hoodie'),(225,'T-shirt'),(250,'Hoodie');

insert into feed_posts (kind, body) values
  ('news','New menu is live at Wok Story. Try the Veg Hakka Noodles this week.'),
  ('poll','Which brand should get a weekend offer?');
insert into poll_options (post_id, label) values
  (2,'The Pizza Galaxy'),(2,'Cheesy Town'),(2,'Wrap n Roll');

-- ========== 6. MAKE YOURSELF ADMIN ==========
-- Sign up in the app first, then run this with your own email:
-- update profiles set role = 'admin' where id = (select id from auth.users where email = 'you@example.com');

-- Refresh PostgREST's schema cache after the tables, functions, and views are created.
notify pgrst, 'reload schema';
