-- EAT60 customer stories: run once in Supabase SQL Editor.
-- Stories are visible only while active. A scheduled cleanup physically removes expired rows.

create extension if not exists pg_cron with schema pg_catalog;

create table if not exists public.feed_stories (
  id bigint generated by default as identity primary key,
  media_url text not null check (media_url ~* '^https?://'),
  media_type text not null check (media_type in ('image', 'video')),
  caption text,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  constraint feed_stories_expiry_after_creation check (expires_at > created_at)
);

grant usage, select on sequence public.feed_stories_id_seq to authenticated;

create index if not exists feed_stories_expiry_idx on public.feed_stories (expires_at);
create index if not exists feed_stories_created_idx on public.feed_stories (created_at desc);

create table if not exists public.feed_story_views (
  story_id bigint not null references public.feed_stories(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (story_id, user_id)
);

alter table public.feed_stories enable row level security;
alter table public.feed_story_views enable row level security;

grant select on public.feed_stories to anon, authenticated;
grant insert, delete on public.feed_stories to authenticated;
grant select on public.feed_story_views to authenticated;

-- Customers can read only unexpired stories; admins can inspect all until cleanup.
drop policy if exists "active stories visible" on public.feed_stories;
create policy "active stories visible" on public.feed_stories
  for select to anon, authenticated
  using (expires_at > now() or public.is_admin());
drop policy if exists "admins publish stories" on public.feed_stories;
create policy "admins publish stories" on public.feed_stories
  for insert to authenticated with check (public.is_admin());
drop policy if exists "admins delete stories" on public.feed_stories;
create policy "admins delete stories" on public.feed_stories
  for delete to authenticated using (public.is_admin());
drop policy if exists "admins read story views" on public.feed_story_views;
drop policy if exists "owners and admins read story views" on public.feed_story_views;
create policy "owners and admins read story views" on public.feed_story_views
  for select to authenticated using (user_id = auth.uid() or public.is_admin());

-- View recording is server-side so viewers cannot read or alter the private totals.
create or replace function public.record_feed_story_view(p_story_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return;
  end if;
  if exists (select 1 from public.feed_stories where id = p_story_id and expires_at > now()) then
    insert into public.feed_story_views (story_id, user_id)
    values (p_story_id, auth.uid())
    on conflict (story_id, user_id) do nothing;
  end if;
end;
$$;
revoke all on function public.record_feed_story_view(bigint) from public;
grant execute on function public.record_feed_story_view(bigint) to authenticated;

-- Supabase projects using pg_cron run cleanup every ten minutes. Expired stories
-- disappear from customer queries immediately, then their media references and views are removed.
create or replace function public.delete_expired_feed_stories()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare deleted_count bigint;
begin
  delete from public.feed_stories where expires_at <= now();
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;
revoke all on function public.delete_expired_feed_stories() from public, anon, authenticated;

do $$
declare existing_job record;
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    for existing_job in select jobid from cron.job where jobname = 'eat60-delete-expired-feed-stories' loop
      perform cron.unschedule(existing_job.jobid);
    end loop;
    perform cron.schedule(
      'eat60-delete-expired-feed-stories',
      '*/10 * * * *',
      'select public.delete_expired_feed_stories();'
    );
  end if;
end;
$$;

do $$ begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'feed_stories') then
    alter publication supabase_realtime add table public.feed_stories;
  end if;
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'feed_story_views') then
    alter publication supabase_realtime add table public.feed_story_views;
  end if;
end $$;

notify pgrst, 'reload schema';

