-- Enables one rating and optional comment per delivered order.
-- Run once in Supabase SQL Editor on an existing installation.
create table if not exists public.order_reviews (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  feedback text check (feedback is null or char_length(feedback) <= 500),
  created_at timestamptz not null default now()
);

alter table public.order_items
  add column if not exists menu_item_id bigint references public.menu_items(id) on delete set null;

update public.order_items oi
set menu_item_id = (
  select i.id
  from public.menu_items i
  where i.brand_id = oi.brand_id
    and split_part(oi.item_name, ' (', 1) = i.name
  order by i.id
  limit 1
)
where oi.menu_item_id is null;

create or replace view public.menu_item_ratings as
  select oi.menu_item_id, round(avg(r.rating)::numeric, 1) as average_rating,
         count(distinct r.id)::int as review_count
  from public.order_items oi
  join public.order_reviews r on r.order_id = oi.order_id
  where oi.menu_item_id is not null
  group by oi.menu_item_id;
grant select on public.menu_item_ratings to anon, authenticated;

alter table public.order_reviews enable row level security;
revoke all on public.order_reviews from public, anon, authenticated;
grant select, insert on public.order_reviews to authenticated;

drop policy if exists "own order review read" on public.order_reviews;
create policy "own order review read" on public.order_reviews
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "review own delivered order" on public.order_reviews;
create policy "review own delivered order" on public.order_reviews
  for insert to authenticated with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.orders o
      where o.id = order_id and o.user_id = auth.uid() and o.status::text = 'delivered'
    )
  );

grant usage, select on sequence public.order_reviews_id_seq to authenticated;
notify pgrst, 'reload schema';
